server:
    servlet:
        context-path: /gestiondecontacts
    port: 8082
spring:
    application:
        name: gestiondecontacts
    jpa:
        defer-datasource-initialization: true
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
        hibernate.ddl-auto: update

    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
            path: /h2-ui
management:
    info:
        java.enabled: true
        os.enabled: true
    endpoint.health:
        show-details: always
    endpoints.web:
        base-path: /
        exposure.include: info, health, refresh, contacts